services:
  testing-karavan:
    container_name: testing-karavan
    environment:
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
    image: localhost:5555/karavan/testing-karavan:latest
    networks:
    - karavan
    ports:
    - 8081:8081
    restart: always
